# Generated by Django 5.0.7 on 2024-12-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
