# Generated by Django 5.0.7 on 2024-12-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='code',
        ),
    ]
