# Generated by Django 5.0.7 on 2025-01-05 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_alter_letter_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='letterprogress',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='letterprogress',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='letterprogress',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='letterprogress',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_recipients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letterprogress',
            name='sent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_sents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letterprogress',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
