# Generated by Django 5.0.7 on 2025-01-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_alter_letterprogress_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
