# Generated by Django 5.0.7 on 2025-01-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterprogress',
            name='is_approved',
        ),
    ]
