# Generated by Django 5.0.7 on 2025-01-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_remove_letterprogress_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='current_user',
        ),
    ]
