# Generated by Django 5.0.7 on 2025-01-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0012_letter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
