# Generated by Django 5.0.7 on 2025-01-20 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0013_alter_letter_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letterprogress',
            options={'ordering': ['-letter__updated']},
        ),
        migrations.AddConstraint(
            model_name='letterprogress',
            constraint=models.UniqueConstraint(fields=('letter', 'sent', 'recipient'), name='unique_progress'),
        ),
    ]
