# Generated by Django 5.0.7 on 2024-12-24 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('dvd_number', models.PositiveSmallIntegerField(default=0)),
                ('info', models.CharField(max_length=455, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employeeuser')),
                ('fond', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.fond')),
                ('received_mtv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_mtv', to='helper.mtv')),
                ('send_mtv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_mtv', to='helper.mtv')),
            ],
        ),
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.TimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='report.report')),
            ],
        ),
    ]
