from main.serializers.poster import PosterSerializer
from main.serializers.information import InformationSerializer, InformationCreateUpdateSerializer
from main.serializers.cadre import CadreSerializer
from main.serializers.serial import SerialSerializer
from main.serializers.bookmark import BookmarkSerializer, BookmarkListSerializer
from main.serializers.rating import RatingCreateUpdateSerializer, RatingSerializer
