# Generated by Django 5.0.7 on 2025-01-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_channelassistantuser_alter_user_role'),
        ('controller', '0002_channel_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.channelassistantuser'),
        ),
    ]
