# Generated by Django 5.0.7 on 2025-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_channel_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
