# Generated by Django 5.0.7 on 2025-01-09 09:22

import authentication.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAssistantUser',
            fields=[
            ],
            options={
                'verbose_name': 'channel assistant',
                'verbose_name_plural': 'channel assistant',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
            managers=[
                ('objects', authentication.managers.ChannelAssistantManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('ARCHIVE_DIRECTOR', 'ARCHIVE_DIRECTOR'), ('CHANNEL_DIRECTOR', 'CHANNEL_DIRECTOR'), ('ARCHIVE_EMPLOYEE', 'ARCHIVE_EMPLOYEE'), ('CHANNEL_ASSISTANT', 'CHANNEL_ASSISTANT'), ('CHANNEL_EMPLOYEE', 'CHANNEL_EMPLOYEE'), ('LOW_USER', 'LOW_USER')], default='LOW_USER', max_length=18),
        ),
    ]
