# Generated by Django 5.0.7 on 2025-01-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_channelassistantuser_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='full name'),
        ),
    ]
